export const ProductService = {
    getProductsData() {
        return [
            {
                id: '1',
                name: 'APPLE iPhone 12 (Blue, 64 GB)',
                price: 42999,
                category: 'smartphone',
                description: 'The iPhone 12 in elegant Blue color with 64GB storage. It features the A14 Bionic Chip for high performance and Next Generation Neural Engine Processor for advanced AI capabilities.',
                processor: 'A14 Bionic Chip with Next Generation Neural Engine Processor',
                storage: '128',
                RAM: '64',
                battery: 'Industry-leading IP68 Water Resistance',
                camera: '12MP + 12MP | 12MP Front Camera',
                display: '15.49 cm (6.1 inch) Super Retina XDR Display',
                inventoryStatus: 'INSTOCK',
                rating: 4,
                inTheBox: 'iPhone, USB-C to Lightning Cable, Documentation',
                modelNumber: 'MGJ83HN/A',
                modelName: 'iPhone 12',
                SIMType: 'Dual Sim',
                quantity: 20,
                image: 'https://rukminim2.flixcart.com/image/416/416/kg8avm80/mobile/y/7/n/apple-iphone-12-dummyapplefsn-original-imafwg8dpyjvgg3j.jpeg',
            },
            {
                id: '2',
                name: 'APPLE iPhone 14 Plus (Starlight, 128 GB)',
                price: 64999,
                category: 'smartphone',
                description: 'The iPhone 14 Plus in stunning Starlight color with 128GB storage. It is powered by the A15 Bionic Chip, 6 Core Processor for enhanced performance and efficiency.',
                processor: 'A15 Bionic Chip, 6 Core Processor Processor',
                storage: '256',
                RAM: '128',
                battery: 'Industry-leading IP68 Water Resistance',
                camera: '12MP + 12MP | 12MP Front Camera',
                display: '17.02 cm (6.7 inch) Super Retina XDR Display',
                inventoryStatus: 'INSTOCK',
                rating: 5,
                inTheBox: 'Handset, USB-C to Lightning Cable, Documentation',
                modelNumber: 'MQ4Y3HN/A',
                modelName: 'iPhone 14 Plus',
                SIMType: 'Dual Sim(Nano + eSIM)',
                quantity: 30,
                image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/l/v/8/-original-imaghx9qudmydgc4.jpeg?q=70',
            },
            {
                id: '3',
                name: 'APPLE iPhone 15 (Blue, 128 GB)',
                price: 77900,
                category: 'smartphone',
                description: 'The iPhone 15 in stylish Blue color with 128GB storage. It boasts the A16 Bionic Chip, 6 Core Processor for cutting-edge performance and advanced camera capabilities.',
                processor: 'A16 Bionic Chip, 6 Core Processor Processor',
                storage: '256',
                RAM: '64',
                battery: 'Industry-leading IP68 Water Resistance',
                camera: '48MP + 12MP | 12MP Front Camera',
                display: '15.49 cm (6.1 inch) Super Retina XDR Display',
                inventoryStatus: 'INSTOCK',
                rating: 5,
                inTheBox: 'Handset, USB C Charge Cable (1m), Documentation',
                modelNumber: 'MTP43HN/A',
                modelName: 'iPhone 15',
                SIMType: 'Dual Sim(Nano + eSIM)',
                quantity: 30,
                image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70',
            },
            {
                id: '4',
                name: 'APPLE iPhone 12 (White, 64 GB)',
                price: 42999,
                category: 'smartphones',
                description: 'The iPhone 12 in pristine White color with 64GB storage. It features the A14 Bionic Chip with Next Generation Neural Engine Processor for superior performance and efficiency.',
                processor: 'A14 Bionic Chip with Next Generation Neural Engine Processor',
                storage: '128',
                RAM: '64',
                battery: 'Industry-leading IP68 Water Resistance',
                camera: '12MP + 12MP | 12MP Front Camera',
                display: '15.49 cm (6.1 inch) Super Retina XDR Display',
                inventoryStatus: 'INSTOCK',
                rating: 4,
                inTheBox: 'iPhone, USB-C to Lightning Cable, Documentation',
                modelNumber: 'MGJ63HN/A',
                modelName: 'iPhone 12',
                SIMType: 'Dual Sim',
                quantity: 12,
                image: 'https://rukminim2.flixcart.com/image/416/416/kg8avm80/mobile/j/f/9/apple-iphone-12-dummyapplefsn-original-imafwg8dkyh2zgrh.jpeg?q=70',
            },
            {
                id: '5',
                name: 'APPLE iPhone 15 Pro Max (Natural Titanium, 256 GB)',
                price: 156900,
                category: 'smartphones',
                description: 'The iPhone 15 Pro Max in stunning Natural Titanium color with 256GB storage. It is powered by the A17 Pro Chip, 6 Core Processor for exceptional performance and advanced camera capabilities.',
                processor: 'A17 Pro Chip, 6 Core Processor Processor',
                storage: '256',
                RAM: '256',
                battery: 'Industry-leading IP68 Water Resistance',
                camera: '48MP + 12MP + 12MP | 12MP Front Camera',
                display: '17.02 cm (6.7 inch) Super Retina XDR Display',
                inventoryStatus: 'INSTOCK',
                rating: 5,
                inTheBox: 'Handset, USB C Charge Cable (1m), Documentation',
                modelNumber: 'MU793HN/A',
                modelName: 'iPhone 15 Pro Max',
                SIMType: 'Dual Sim(Nano + eSIM)',
                quantity: 10,
                image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/p/q/i/-original-imagtc3kfyhgfcvr.jpeg?q=70',
            },
            {
                id: "1",
                name: "APPLE iPhone 13 (Pink, 128 GB)",
                price: 58900,
                category: "smartphones",
                description: "The latest iPhone with A15 Bionic Chip and dual-camera system.",
                processor: "A15 Bionic Chip Processor",
                storage: "128",
                RAM: "6",
                battery: "3100 mAh",
                camera: "12MP + 12MP | 12MP Front Camera",
                display: "6.1 inches, Super Retina XDR",
                inventoryStatus: "INSTOCK",
                rating: 4.9,
                inTheBox: "iPhone, USB-C to Lightning Cable, Documentation",
                modelNumber: "MLPH3HN/A",
                modelName: "iPhone 13",
                SIMType: "Dual Sim",
                quantity: 10,
                image: "https://rukminim2.flixcart.com/image/416/416/ktketu80/mobile/8/z/w/iphone-13-mlph3hn-a-apple-original-imag6vzzhrxgazsg.jpeg?q=70"
            },
            {
                id: "2",
                name: "Samsung Galaxy S21 (Black, 256 GB)",
                price: 69999,
                category: "smartphones",
                description: "Powerful Samsung flagship with Exynos 2100 and 108MP camera.",
                processor: "Exynos 2100 Processor",
                storage: "256",
                RAM: "8",
                battery: "4000 mAh",
                camera: "108MP + 12MP + 10MP | 40MP Front Camera",
                display: "6.2 inches, Dynamic AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Samsung Galaxy S21, Charger, USB Cable, Earphones, Documentation",
                modelNumber: "SM-G991B/DS",
                modelName: "Galaxy S21",
                SIMType: "Nano Sim",
                quantity: 8,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/d/o/r/-original-imagu4haetzha9bj.jpeg?q=70"
            },
            {
                id: "4",
                name: "Xiaomi Redmi Note 10 (White, 64 GB)",
                price: 13999,
                category: "smartphones",
                description: "Affordable and feature-packed smartphone from Xiaomi.",
                processor: "Snapdragon 678 Processor",
                storage: "64",
                RAM: "4",
                battery: "5000 mAh",
                camera: "48MP + 8MP + 2MP + 2MP | 13MP Front Camera",
                display: "6.43 inches, Super AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "Redmi Note 10, Charger, USB Cable, Documentation",
                modelNumber: "M2101K7AI",
                modelName: "Note 10",
                SIMType: "Dual Sim",
                quantity: 20,
                image: "https://rukminim2.flixcart.com/image/416/416/kv1a4cw0/mobile/t/v/3/note-10-lite-2109106a1i-redmi-original-imag8yuh2gpuxfha.jpeg?q=70"
            },
            {
                id: "11",
                name: "OnePlus 9 Pro (Morning Mist, 256 GB)",
                price: 64999,
                category: "smartphones",
                description: "Experience flagship performance with Hasselblad cameras.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "12",
                battery: "4500 mAh",
                camera: "48MP + 50MP + 8MP + 2MP | 16MP Front Camera",
                display: "6.7 inches, Fluid AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "OnePlus 9 Pro, Warp Charge 65 Power Adapter, Warp Charge Type-C to Type-C Cable, Quick Start Guide",
                modelNumber: "LE2120",
                modelName: "9 Pro",
                SIMType: "Dual Sim",
                quantity: 8,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/z/l/-original-imagdm2pzrg5ej6y.jpeg?q=70"
            },
            {
                id: "12",
                name: "Google Pixel 6 (Sorta Sage, 128 GB)",
                price: 69999,
                category: "smartphones",
                description: "Capture stunning photos with the Google Pixel's advanced AI camera.",
                processor: "Google Tensor Processor",
                storage: "128",
                RAM: "8",
                battery: "4600 mAh",
                camera: "50MP + 12MP | 8MP Front Camera",
                display: "6.4 inches, AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Google Pixel 6, 18W USB-C Power Adapter, USB-C to USB-C Cable (1m), SIM Tool, Quick Start Guide",
                modelNumber: "G020N",
                modelName: "Pixel 6",
                SIMType: "eSIM",
                quantity: 3,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/g/g/3/-original-imaggbrccwsnygar.jpeg?q=70"
            },
            {
                id: "14",
                name: "Motorola Moto G Power (Flash Gray, 64 GB)",
                price: 19999,
                category: "smartphones",
                description: "Long-lasting battery life and a budget-friendly price.",
                processor: "Qualcomm Snapdragon 662 Processor",
                storage: "64",
                RAM: "4",
                battery: "5000 mAh",
                camera: "48MP + 2MP + 2MP | 8MP Front Camera",
                display: "6.6 inches, IPS LCD",
                inventoryStatus: "LOWSTOCK",
                rating: 4.5,
                inTheBox: "Moto G Power, 10W Charger, USB-C Cable, Guides",
                modelNumber: "PAMH0000US",
                modelName: "Moto G Power",
                SIMType: "Nano Sim",
                quantity: 3,
                image: "https://rukminim2.flixcart.com/image/416/416/kl9rssw0/mobile/r/i/z/e7-power-pamh0013in-pamh0011in-pamh0016in-motorola-original-imagyfu4dh6jgbgx.jpeg?q=70"
            },
            {
                id: "15",
                name: "Nokia 8.3 5G (Polar Night, 128 GB)",
                price: 54999,
                category: "smartphones",
                description: "A Nokia phone with 5G connectivity and PureView quad-camera setup.",
                processor: "Qualcomm Snapdragon 765G Processor",
                storage: "128",
                RAM: "8",
                battery: "4500 mAh",
                camera: "64MP + 12MP + 2MP + 2MP | 24MP Front Camera",
                display: "6.81 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.6,
                inTheBox: "Nokia 8.3 5G, Charger, USB Type-C Cable, Quick Start Guide",
                modelNumber: "TA-1243",
                modelName: "8.3 5G",
                SIMType: "Nano Sim",
                quantity: 6,
                image: "https://rukminim2.flixcart.com/image/416/416/kkwwu4w0/mobile/p/w/j/5-4-hq5020m514000-nokia-original-imagy5bqzkcezvpq.jpeg?q=70"
            },
            {
                id: "17",
                name: "Asus ROG Phone 5 (Phantom Black, 256 GB)",
                price: 59999,
                category: "smartphones",
                description: "Designed for mobile gaming with Snapdragon 888 and a 144Hz AMOLED display.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "12",
                battery: "6000 mAh",
                camera: "64MP + 13MP + 5MP | 24MP Front Camera",
                display: "6.78 inches, AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Asus ROG Phone 5, AeroActive Cooler 5, Charger, USB-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "ZS673KS",
                modelName: "ROG Phone 5",
                SIMType: "Nano Sim",
                quantity: 2,
                image: "https://rukminim2.flixcart.com/image/416/416/ky7lci80/mobile/l/j/q/-original-imagahvnprnrt4xq.jpeg?q=70"
            },
            {
                id: "19",
                name: "Xiaomi Redmi 10 (Pebble White, 64 GB)",
                price: 12999,
                category: "smartphones",
                description: "An affordable and feature-packed phone with a large display.",
                processor: "MediaTek Helio G88 Processor",
                storage: "64",
                RAM: "4",
                battery: "5000 mAh",
                camera: "50MP + 8MP + 2MP + 2MP | 8MP Front Camera",
                display: "6.5 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.4,
                inTheBox: "Xiaomi Redmi 10, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "M2106F9SH",
                modelName: "Redmi 10",
                SIMType: "Nano Sim",
                quantity: 7,
                image: "https://rukminim2.flixcart.com/image/416/416/l3dcl8w0/mobile/o/k/1/10-prime-2022-22011119tl-redmi-original-imagegdjhcshnsh8.jpeg?q=70"
            },
            {
                id: "21",
                name: "Apple iPhone 13 Pro Max (Graphite, 256 GB)",
                price: 129900,
                category: "smartphones",
                description: "The larger iPhone 13 Pro model with ProMotion display and improved camera system.",
                processor: "A15 Bionic Chip Processor",
                storage: "256",
                RAM: "6",
                battery: "4352 mAh",
                camera: "12MP + 12MP + 12MP + TOF 3D | 12MP Front Camera",
                display: "6.7 inches, Super Retina XDR ProMotion",
                inventoryStatus: "INSTOCK",
                rating: 4.9,
                inTheBox: "iPhone, USB-C to Lightning Cable, Documentation",
                modelNumber: "MLLJ3HN/A",
                modelName: "iPhone 13 Pro Max",
                SIMType: "Dual Sim",
                quantity: 8,
                image: "https://rukminim2.flixcart.com/image/416/416/kg8avm80/mobile/5/z/w/apple-iphone-12-pro-max-dummyapplefsn-original-imafwgcy7ugz3y2z.jpeg?q=70"
            },
            {
                id: "22",
                name: "Samsung Galaxy Z Fold 3 (Phantom Black, 256 GB)",
                price: 174999,
                category: "smartphones",
                description: "A foldable Samsung phone with S Pen support and large AMOLED displays.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "12",
                battery: "4400 mAh",
                camera: "12MP + 12MP + 12MP | 10MP Front Camera",
                display: "7.6 inches (Main), 6.2 inches (Cover), AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Samsung Galaxy Z Fold 3, S Pen, Charger, USB-C Cable, Earphones, Documentation",
                modelNumber: "SM-F926B",
                modelName: "Galaxy Z Fold 3",
                SIMType: "Nano Sim",
                quantity: 6,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/f/n/h/-original-imagh7nzh2gcdj2x.jpeg?q=70"
            },
            {
                id: "23",
                name: "OnePlus Nord 2 (Blue Haze, 128 GB)",
                price: 29999,
                category: "smartphones",
                description: "Mid-range OnePlus phone with MediaTek Dimensity 1200 AI and 90Hz AMOLED display.",
                processor: "MediaTek Dimensity 1200 AI Processor",
                storage: "128",
                RAM: "8",
                battery: "4500 mAh",
                camera: "50MP + 8MP + 2MP | 32MP Front Camera",
                display: "6.43 inches, Fluid AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "OnePlus Nord 2, Warp Charge 65 Power Adapter, Warp Charge Type-C to Type-C Cable, Quick Start Guide",
                modelNumber: "N2002",
                modelName: "Nord 2",
                SIMType: "Dual Sim",
                quantity: 4,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/b/b/e/-original-imagbd6bmq3bh4wd.jpeg?q=70"
            },
            {
                id: "24",
                name: "Google Pixel 5a (Mostly Black, 128 GB)",
                price: 44999,
                category: "smartphones",
                description: "A budget-friendly Pixel phone with a focus on camera quality and clean Android experience.",
                processor: "Qualcomm Snapdragon 765G Processor",
                storage: "128",
                RAM: "6",
                battery: "4680 mAh",
                camera: "12.2MP + 16MP | 8MP Front Camera",
                display: "6.34 inches, OLED",
                inventoryStatus: "INSTOCK",
                rating: 4.6,
                inTheBox: "Google Pixel 5a, 18W USB-C Power Adapter, USB-C to USB-C Cable (1m), SIM Tool, Quick Start Guide",
                modelNumber: "GD1YQ",
                modelName: "Pixel 5a",
                SIMType: "eSIM",
                quantity: 2,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/z/b/d/-original-imagpgx48f4szdvf.jpeg?q=70"
            },
            {
                id: "25",
                name: "Realme GT Master Edition (Lunar Black, 128 GB)",
                price: 25999,
                category: "smartphones",
                description: "Collaboration with Naoto Fukasawa, offering a distinctive design and performance.",
                processor: "Qualcomm Snapdragon 778G Processor",
                storage: "128",
                RAM: "8",
                battery: "4300 mAh",
                camera: "64MP + 8MP + 2MP | 32MP Front Camera",
                display: "6.43 inches, Super AMOLED",
                inventoryStatus: "LOWSTOCK",
                rating: 4.5,
                inTheBox: "Realme GT Master Edition, SuperDart Charge 65W Adapter, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "RMX3366",
                modelName: "GT Master Edition",
                SIMType: "Dual Sim",
                quantity: 3,
                image: "https://rukminim2.flixcart.com/image/416/416/l3rmzrk0/mobile/p/b/o/-original-imagetme8brtujft.jpeg?q=70"
            },
            {
                id: "27",
                name: "Vivo Y72 5G (Dream Glow, 128 GB)",
                price: 20990,
                category: "smartphones",
                description: "A 5G-enabled mid-range phone with a large display and dual-camera setup.",
                processor: "MediaTek Dimensity 700 Processor",
                storage: "128",
                RAM: "8",
                battery: "5000 mAh",
                camera: "64MP + 2MP | 16MP Front Camera",
                display: "6.58 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.4,
                inTheBox: "Vivo Y72 5G, Charger, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "V2059",
                modelName: "Y72 5G",
                SIMType: "Dual Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/kr3tj0w0/mobile/a/d/i/y72-5g-v2060-vivo-original-imag4yngqqjqvvht.jpeg?q=70"
            },
            {
                id: "28",
                name: "Oppo Reno6 Pro 5G (Aurora, 256 GB)",
                price: 39990,
                category: "smartphones",
                description: "A stylish Oppo phone with 5G capabilities and a focus on camera performance.",
                processor: "MediaTek Dimensity 1200 Processor",
                storage: "256",
                RAM: "12",
                battery: "4500 mAh",
                camera: "64MP + 8MP + 2MP + 2MP | 32MP Front Camera",
                display: "6.55 inches, AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.6,
                inTheBox: "Oppo Reno6 Pro 5G, Charger, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "CPH2249",
                modelName: "Reno6 Pro 5G",
                SIMType: "Nano Sim",
                quantity: 0,
                image: "https://rukminim2.flixcart.com/image/416/416/kr2e3680/mobile/i/c/l/reno6-pro-5g-cph2249-oppo-original-imag4xpchmrsqdru.jpeg?q=70"
            },
            {
                id: "29",
                name: "Motorola Edge 20 Fusion (Electric Graphite, 128 GB)",
                price: 21999,
                category: "smartphones",
                description: "A Motorola phone with a focus on camera versatility and battery life.",
                processor: "MediaTek Dimensity 800U Processor",
                storage: "128",
                RAM: "6",
                battery: "5000 mAh",
                camera: "108MP + 8MP + 2MP | 32MP Front Camera",
                display: "6.7 inches, IPS LCD",
                inventoryStatus: "LOWSTOCK",
                rating: 4.5,
                inTheBox: "Motorola Edge 20 Fusion, 30W TurboPower Charger, USB Type-C Cable, Guides",
                modelNumber: "PAMR0001IN",
                modelName: "Edge 20 Fusion",
                SIMType: "Hybrid Dual Sim",
                quantity: 2,
                image: "https://rukminim2.flixcart.com/image/416/416/ksez24w0/mobile/b/m/h/edge-20-fusion-parf0010in-motorola-original-imag5yvbfuykjveb.jpeg?q=70"
            },
            {
                id: "31",
                name: "LG Wing 5G (Aurora Gray, 256 GB)",
                price: 44990,
                category: "smartphones",
                description: "A unique dual-screen LG phone with a swiveling display for multitasking.",
                processor: "Qualcomm Snapdragon 765G Processor",
                storage: "256",
                RAM: "8",
                battery: "4000 mAh",
                camera: "64MP + 13MP + 12MP | 32MP Front Camera",
                display: "6.8 inches, P-OLED",
                inventoryStatus: "INSTOCK",
                rating: 4.6,
                inTheBox: "LG Wing 5G, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "LM-F100EMW",
                modelName: "Wing 5G",
                SIMType: "Nano Sim",
                quantity: 10,
                image: "https://rukminim2.flixcart.com/image/416/416/kiew3gw0/mobile/4/f/k/lg-wing-lmf100emw-ainday-original-imafy7g8hrf2tytc.jpeg?q=70"
            },
            {
                id: "33",
                name: "Apple iPhone SE (Red, 64 GB)",
                price: 39900,
                category: "smartphones",
                description: "A compact iPhone with the latest A15 Bionic chip for enhanced performance.",
                processor: "A15 Bionic Chip Processor",
                storage: "64",
                RAM: "4",
                battery: "1821 mAh",
                camera: "12MP | 7MP Front Camera",
                display: "4.7 inches, Retina HD",
                inventoryStatus: "LOWSTOCK",
                rating: 4.7,
                inTheBox: "iPhone SE, Charger, USB-C to Lightning Cable, EarPods with Lightning Connector",
                modelNumber: "MYK62HN/A",
                modelName: "iPhone SE",
                SIMType: "Nano Sim",
                quantity: 3,
                image: "https://rukminim2.flixcart.com/image/416/416/l0igvww0/mobile/9/6/t/-original-imagca67gxuvkmrj.jpeg?q=70"
            },
            {
                id: "35",
                name: "Xiaomi Redmi Note 10 Pro (Glacial Blue, 128 GB)",
                price: 17999,
                category: "smartphones",
                description: "Redmi Note 10 Pro with a high-refresh-rate display and versatile camera setup.",
                processor: "Qualcomm Snapdragon 732G Processor",
                storage: "128",
                RAM: "6",
                battery: "5020 mAh",
                camera: "64MP + 8MP + 5MP + 2MP | 16MP Front Camera",
                display: "6.67 inches, Super AMOLED",
                inventoryStatus: "LOWSTOCK",
                rating: 4.6,
                inTheBox: "Xiaomi Redmi Note 10 Pro, Charger, USB Type-C Cable, SIM Ejector Tool, Protective Case, User Guide",
                modelNumber: "M2101K6I",
                modelName: "Redmi Note 10 Pro",
                SIMType: "Dual Sim",
                quantity: 2,
                image: "https://rukminim2.flixcart.com/image/416/416/l0h1g280/mobile/z/i/7/-original-imagc9cqfgjjam9z.jpeg?q=70"
            },
            {
                id: "36",
                name: "Vivo V21e (Diamond Flare, 128 GB)",
                price: 25990,
                category: "smartphones",
                description: "A stylish Vivo phone with a focus on slim design and a high-resolution front camera.",
                processor: "MediaTek Dimensity 800U Processor",
                storage: "128",
                RAM: "8",
                battery: "4000 mAh",
                camera: "64MP + 8MP + 2MP | 44MP Front Camera",
                display: "6.44 inches, AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.5,
                inTheBox: "Vivo V21e, Charger, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "V2055",
                modelName: "V21e",
                SIMType: "Dual Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/ktuewsw0/screen-guard/edge-to-edge-screen-guard/n/s/l/vivo-y21-sbc-original-imag72xwa8bhtvp2.jpeg?q=70"
            },
            {
                id: "38",
                name: "Motorola Moto E7 Plus (Misty Blue, 64 GB)",
                price: 9999,
                category: "smartphones",
                description: "A budget-friendly Moto phone with a large display and a dual-camera setup.",
                processor: "Qualcomm Snapdragon 460 Processor",
                storage: "64",
                RAM: "4",
                battery: "5000 mAh",
                camera: "48MP + 2MP | 8MP Front Camera",
                display: "6.5 inches, IPS LCD",
                inventoryStatus: "LOWSTOCK",
                rating: 4.3,
                inTheBox: "Motorola Moto E7 Plus, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "PAMH0003IN",
                modelName: "Moto E7 Plus",
                SIMType: "Dual Sim",
                quantity: 1,
                image: "https://rukminim2.flixcart.com/image/416/416/kesv0y80/mobile/d/z/u/motorola-e7-plus-pakx0012in-original-imafved7zdzgd7hq.jpeg?q=70"
            },
            {
                id: "40",
                name: "Sony Xperia 10 III (Black, 128 GB)",
                price: 34999,
                category: "smartphones",
                description: "Sony Xperia phone with a triple-camera system and 21:9 OLED display.",
                processor: "Qualcomm Snapdragon 690 Processor",
                storage: "128",
                RAM: "6",
                battery: "4500 mAh",
                camera: "12MP + 8MP + 8MP | 8MP Front Camera",
                display: "6 inches, OLED",
                inventoryStatus: "INSTOCK",
                rating: 4.5,
                inTheBox: "Sony Xperia 10 III, Charger, USB Type-C Cable, Headset, Documentation",
                modelNumber: "XQ-BT52",
                modelName: "Xperia 10 III",
                SIMType: "Nano Sim",
                quantity: 4,
                image: "https://rukminim2.flixcart.com/image/416/416/mobile/b/a/y/sony-xperia-xz-original-imaenjgayzzdbspg.jpeg?q=70"
            },
            {
                id: "41",
                name: "Samsung Galaxy M32 (Light Blue, 128 GB)",
                price: 16999,
                category: "smartphones",
                description: "Samsung Galaxy phone with a high-refresh-rate display and a versatile camera setup.",
                processor: "MediaTek Helio G80 Processor",
                storage: "128",
                RAM: "6",
                battery: "6000 mAh",
                camera: "64MP + 8MP + 2MP + 2MP | 20MP Front Camera",
                display: "6.4 inches, Super AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.5,
                inTheBox: "Samsung Galaxy M32, Charger, USB Type-C Cable, Earphones, SIM Ejector Tool, Documentation",
                modelNumber: "SM-M325FZBDINS",
                modelName: "Galaxy M32",
                SIMType: "Dual Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/r/f/n/-original-imagjhr894wgfzzc.jpeg?q=70"
            },
            {
                id: "42",
                name: "OnePlus 9 Pro (Morning Mist, 256 GB)",
                price: 69999,
                category: "smartphones",
                description: "OnePlus flagship with a Hasselblad camera system and powerful Snapdragon 888 processor.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "12",
                battery: "4500 mAh",
                camera: "48MP + 50MP + 8MP + 2MP | 16MP Front Camera",
                display: "6.7 inches, Fluid AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "OnePlus 9 Pro, Warp Charge 65 Power Adapter, Warp Charge Type-C to Type-C Cable, Quick Start Guide, Welcome Letter, Safety Information and Warranty Card, Logo Sticker, Case, Screen Protector, SIM Tray Ejector",
                modelNumber: "LE2120",
                modelName: "9 Pro",
                SIMType: "Dual Sim",
                quantity: 8,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/e/z/l/-original-imagdm2pzrg5ej6y.jpeg?q=70"
            },
            {
                id: "46",
                name: "Sony Xperia 5 III (Black, 256 GB)",
                price: 79999,
                category: "smartphones",
                description: "Sony Xperia phone with a triple-camera system and 120Hz refresh rate display.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "8",
                battery: "4500 mAh",
                camera: "12MP + 12MP + 12MP | 8MP Front Camera",
                display: "6.1 inches, OLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "Sony Xperia 5 III, Charger, USB Type-C Cable, Headset, Documentation",
                modelNumber: "XQ-BC72",
                modelName: "Xperia 5 III",
                SIMType: "Nano Sim",
                quantity: 4,
                image: "https://rukminim2.flixcart.com/image/416/416/j8ndea80/mobile/p/x/q/sony-xperia-xa1-plus-g3416-original-imaeym7pbansm3ns.jpeg?q=70"
            },
            {
                id: "47",
                name: "Realme GT 5G (Dashing Silver, 128 GB)",
                price: 27999,
                category: "smartphones",
                description: "Realme phone with 5G capabilities and a focus on high performance.",
                processor: "Qualcomm Snapdragon 870 Processor",
                storage: "128",
                RAM: "8",
                battery: "4500 mAh",
                camera: "64MP + 8MP + 2MP | 16MP Front Camera",
                display: "6.43 inches, Super AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.6,
                inTheBox: "Realme GT 5G, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "RMX2202",
                modelName: "GT 5G",
                SIMType: "Dual Sim",
                quantity: 7,
                image: "https://rukminim2.flixcart.com/image/416/416/l3rmzrk0/mobile/f/z/n/-original-imagetme3gzbnc3z.jpeg?q=70"
            },
            {
                id: "48",
                name: "LG Velvet (Aurora White, 128 GB)",
                price: 34990,
                category: "smartphones",
                description: "LG Velvet with a sleek design and dual-screen accessory support.",
                processor: "Qualcomm Snapdragon 765G Processor",
                storage: "128",
                RAM: "6",
                battery: "4300 mAh",
                camera: "48MP + 8MP + 5MP | 16MP Front Camera",
                display: "6.8 inches, P-OLED",
                inventoryStatus: "LOWSTOCK",
                rating: 4.4,
                inTheBox: "LG Velvet, Charger, USB Type-C Cable, Earphones, SIM Ejector Tool, Documentation",
                modelNumber: "LM-G900EMW",
                modelName: "Velvet",
                SIMType: "Nano Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/kgsb1jk0/mobile/h/r/e/lg-velvet-dual-screen-lmg910emw-original-imafwy7ytk8y3ucw.jpeg?q=70"
            },
            {
                id: "49",
                name: "Vivo X60 Pro+ (Orange, 256 GB)",
                price: 79990,
                category: "smartphones",
                description: "Vivo flagship with a focus on photography and high-end specifications.",
                processor: "Qualcomm Snapdragon 888 Processor",
                storage: "256",
                RAM: "12",
                battery: "4200 mAh",
                camera: "50MP + 48MP + 32MP + 8MP | 32MP Front Camera",
                display: "6.56 inches, AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Vivo X60 Pro+, Charger, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "V2056",
                modelName: "X60 Pro+",
                SIMType: "Dual Sim",
                quantity: 3,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/w/g/k/narzo-60-pro-5g-rmx3771-realme-original-imagrhu7fraevevd.jpeg?q=70"
            },
            {
                id: "50",
                name: "Motorola Moto G60 (Dynamic Gray, 128 GB)",
                price: 17999,
                category: "smartphones",
                description: "Motorola Moto G phone with a large battery and a 108MP camera.",
                processor: "Qualcomm Snapdragon 732G Processor",
                storage: "128",
                RAM: "6",
                battery: "6000 mAh",
                camera: "108MP + 8MP + 2MP | 32MP Front Camera",
                display: "6.8 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.4,
                inTheBox: "Motorola Moto G60, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "PAMH0000IN",
                modelName: "Moto G60",
                SIMType: "Hybrid Dual Sim",
                quantity: 6,
                image: "https://rukminim2.flixcart.com/image/416/416/knoxnrk0/mobile/x/0/o/g60-panb0000in-panb0016in-panb0012in-panb0014in-motorola-original-imag2aq97yw3gvhj.jpeg?q=70"
            },
            {
                id: "52",
                name: "Xiaomi Redmi Note 10S (Deep Sea Blue, 128 GB)",
                price: 15999,
                category: "smartphones",
                description: "Redmi Note 10S with a quad-camera setup and a high-refresh-rate display.",
                processor: "MediaTek Helio G95 Processor",
                storage: "128",
                RAM: "6",
                battery: "5000 mAh",
                camera: "64MP + 8MP + 2MP + 2MP | 13MP Front Camera",
                display: "6.43 inches, Super AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.5,
                inTheBox: "Xiaomi Redmi Note 10S, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "M2101K7BI",
                modelName: "Redmi Note 10S",
                SIMType: "Dual Sim",
                quantity: 6,
                image: "https://rukminim2.flixcart.com/image/416/416/kyeqjrk0/mobile/y/i/j/-original-imagan9qdzcc7hbb.jpeg?q=70"
            },
            {
                id: "53",
                name: "Vivo Y53s (Fantastic Rainbow, 128 GB)",
                price: 19990,
                category: "smartphones",
                description: "Vivo Y53s with a focus on design and a dual-camera setup.",
                processor: "MediaTek Helio G80 Processor",
                storage: "128",
                RAM: "8",
                battery: "5000 mAh",
                camera: "64MP + 2MP | 16MP Front Camera",
                display: "6.58 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.3,
                inTheBox: "Vivo Y53s, Charger, USB Type-C Cable, Earphones, Documentation",
                modelNumber: "V2057",
                modelName: "Y53s",
                SIMType: "Dual Sim",
                quantity: 4,
                image: "https://rukminim2.flixcart.com/image/416/416/ks3jjbk0/mobile/e/4/f/y53s-v2058-vivo-original-imag5q36dcxquhjh.jpeg?q=70"
            },
            {
                id: "54",
                name: "OnePlus 9R (Lake Blue, 128 GB)",
                price: 39999,
                category: "smartphones",
                description: "OnePlus 9R with a focus on gaming performance and a versatile camera system.",
                processor: "Qualcomm Snapdragon 870 Processor",
                storage: "128",
                RAM: "8",
                battery: "4500 mAh",
                camera: "48MP + 16MP + 5MP + 2MP | 16MP Front Camera",
                display: "6.55 inches, Fluid AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.7,
                inTheBox: "OnePlus 9R, Warp Charge 65 Power Adapter, Warp Charge Type-C to Type-C Cable, Quick Start Guide",
                modelNumber: "LE2100",
                modelName: "9R",
                SIMType: "Nano Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/q/f/o/-original-imagdnatanzxwsjb.jpeg?q=70"
            },
            {
                id: "57",
                name: "Xiaomi Mi 11X (Cosmic Black, 128 GB)",
                price: 29999,
                category: "smartphones",
                description: "Xiaomi Mi 11X with a Snapdragon 870 processor and a 120Hz AMOLED display.",
                processor: "Qualcomm Snapdragon 870 Processor",
                storage: "128",
                RAM: "6",
                battery: "4520 mAh",
                camera: "48MP + 8MP + 5MP | 20MP Front Camera",
                display: "6.67 inches, Super AMOLED",
                inventoryStatus: "INSTOCK",
                rating: 4.8,
                inTheBox: "Xiaomi Mi 11X, Charger, USB Type-C Cable, SIM Ejector Tool, Protective Case, User Guide",
                modelNumber: "M2012K11AI",
                modelName: "Mi 11X",
                SIMType: "Dual Sim",
                quantity: 8,
                image: "https://rukminim2.flixcart.com/image/416/416/kod858w0/mobile/s/7/d/11x-pro-11x-pro-mi-original-imag2tzj6jjbkgwz.jpeg?q=70"
            },
            {
                id: "60",
                name: "Motorola Moto G60 (Dynamic Gray, 128 GB)",
                price: 17999,
                category: "smartphones",
                description: "Motorola Moto G60 with a large battery and a 108MP camera.",
                processor: "Qualcomm Snapdragon 732G Processor",
                storage: "128",
                RAM: "6",
                battery: "6000 mAh",
                camera: "108MP + 8MP + 2MP | 32MP Front Camera",
                display: "6.8 inches, IPS LCD",
                inventoryStatus: "INSTOCK",
                rating: 4.5,
                inTheBox: "Motorola Moto G60, Charger, USB Type-C Cable, SIM Ejector Tool, Documentation",
                modelNumber: "PAMH0000IN",
                modelName: "Moto G60",
                SIMType: "Hybrid Dual Sim",
                quantity: 5,
                image: "https://rukminim2.flixcart.com/image/416/416/knoxnrk0/mobile/x/0/o/g60-panb0000in-panb0016in-panb0012in-panb0014in-motorola-original-imag2aq97yw3gvhj.jpeg?q=70"
            }

        ];
    },

    getProductsMini() {
        return Promise.resolve(this.getProductsData().slice(0, 5));
    },

    getProductsSmall() {
        return Promise.resolve(this.getProductsData().slice(0, 10));
    },

    getProducts() {
        return Promise.resolve(this.getProductsData());
    },

    getProductsWithOrdersSmall() {
        return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
    },

    getProductsWithOrders() {
        return Promise.resolve(this.getProductsWithOrdersData());
    }
};

